language: node_js

node_js: node

before_install:
  - npm install -g gulp
  - sudo apt-get install imagemagick

install: npm install

os: linux

script: npm run coverage

after_script: cat ./coverage/lcov.info | coveralls.js
