dist: xenial

language: node_js

node_js: node

addons:
  apt:
    packages:
    - imagemagick

before_install:
  - yarn global add gulp

script:
  - yarn convert
  - yarn cover:lcov

after_script: yarn cover:write
